"""v01_initial_schema

Revision ID: 0d7ca46f885c
Revises: 
Create Date: 2026-08-03 15:30:18.554976
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d7ca46f885c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAJA', 'INFO', name='severity'), nullable=False),
    sa.Column('dsl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version')
    )
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_format', sa.String(length=50), nullable=False),
    sa.Column('source_file_name', sa.String(length=500), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'PARSED', 'NORMALIZING', 'NORMALIZED', 'EXTRACTING', 'EXTRACTED', 'CORRELATING', 'CORRELATED', 'MATERIALIZING', 'MATERIALIZED', 'RULES', 'COMPLETED', 'FAILED', 'PAUSED', name='import_status'), nullable=False),
    sa.Column('stage_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pipeline_version', sa.String(length=20), nullable=True),
    sa.Column('redaction_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('host_pattern', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cardinality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restricted', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('EVIDENCIA', 'INFERENCIA', 'HIPOTESIS', name='confidence_level'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'method', 'pattern', 'host_pattern')
    )
    op.create_table('import_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('parse', 'normalize', 'extract', 'correlate', 'materialize', 'rules', name='stage_name'), nullable=False),
    sa.Column('shard', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='stage_status'), nullable=False),
    sa.Column('processed', sa.BigInteger(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'stage', 'shard')
    )
    op.create_table('parse_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw_fragment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rules_checked', sa.Integer(), nullable=False),
    sa.Column('alerts_created', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='run_status'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_run_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAJA', 'INFO', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'FALSE_POSITIVE', 'CONFIRMED', 'CLOSED', name='alert_status'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_subgraph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['rule_run_id'], ['rule_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('param', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['endpoint_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_values_template_id'), 'endpoint_values', ['template_id'], unique=False)
    op.create_table('http_exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('scheme', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('path_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('req_headers_count', sa.Integer(), nullable=False),
    sa.Column('resp_status_code', sa.Integer(), nullable=False),
    sa.Column('resp_headers_count', sa.Integer(), nullable=False),
    sa.Column('req_has_json', sa.Boolean(), nullable=False),
    sa.Column('resp_has_json', sa.Boolean(), nullable=False),
    sa.Column('req_body_size', sa.BigInteger(), nullable=True),
    sa.Column('resp_body_size', sa.BigInteger(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['endpoint_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_http_exchanges_host', 'http_exchanges', ['host'], unique=False)
    op.create_index(op.f('ix_http_exchanges_import_id'), 'http_exchanges', ['import_id'], unique=False)
    op.create_index('ix_http_exchanges_import_order', 'http_exchanges', ['import_id', 'order'], unique=False)
    op.create_index(op.f('ix_http_exchanges_template_id'), 'http_exchanges', ['template_id'], unique=False)
    op.create_table('body_json',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('request', 'response', name='body_direction'), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_sha256', sa.String(length=64), nullable=True),
    sa.Column('stored_bytes', sa.BigInteger(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['http_exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_json_exchange_id'), 'body_json', ['exchange_id'], unique=False)
    op.create_table('entity_occurrences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('location', sa.Enum('request.header', 'request.query', 'request.body', 'request.cookie', 'response.header', 'response.body', 'response.cookie', 'path', name='location_enum'), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['http_exchanges.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_occurrences_exchange_id'), 'entity_occurrences', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_entity_occurrences_import_id'), 'entity_occurrences', ['import_id'], unique=False)
    op.create_index('ix_occurrences_type_label_hash', 'entity_occurrences', ['entity_type', 'entity_label', 'value_hash'], unique=False)
    op.create_index('ix_occurrences_value_hash', 'entity_occurrences', ['value_hash'], unique=False)
    op.create_table('http_cookies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('request', 'response', name='cookie_direction'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_hash', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['http_exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_cookies_exchange_id'), 'http_cookies', ['exchange_id'], unique=False)
    op.create_table('http_headers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('request', 'response', name='header_direction'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_hash', sa.String(length=64), nullable=True),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['http_exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_headers_exchange_id'), 'http_headers', ['exchange_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_http_headers_exchange_id'), table_name='http_headers')
    op.drop_table('http_headers')
    op.drop_index(op.f('ix_http_cookies_exchange_id'), table_name='http_cookies')
    op.drop_table('http_cookies')
    op.drop_index('ix_occurrences_value_hash', table_name='entity_occurrences')
    op.drop_index('ix_occurrences_type_label_hash', table_name='entity_occurrences')
    op.drop_index(op.f('ix_entity_occurrences_import_id'), table_name='entity_occurrences')
    op.drop_index(op.f('ix_entity_occurrences_exchange_id'), table_name='entity_occurrences')
    op.drop_table('entity_occurrences')
    op.drop_index(op.f('ix_body_json_exchange_id'), table_name='body_json')
    op.drop_table('body_json')
    op.drop_index(op.f('ix_http_exchanges_template_id'), table_name='http_exchanges')
    op.drop_index('ix_http_exchanges_import_order', table_name='http_exchanges')
    op.drop_index(op.f('ix_http_exchanges_import_id'), table_name='http_exchanges')
    op.drop_index('ix_http_exchanges_host', table_name='http_exchanges')
    op.drop_table('http_exchanges')
    op.drop_index(op.f('ix_endpoint_values_template_id'), table_name='endpoint_values')
    op.drop_table('endpoint_values')
    op.drop_table('alerts')
    op.drop_table('rule_runs')
    op.drop_table('parse_errors')
    op.drop_table('import_stages')
    op.drop_table('endpoint_templates')
    op.drop_table('imports')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###